{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "leancd.serviceAccountName" . }}
  namespace: {{ include "leancd.namespace" . }}
  labels:
    {{- include "leancd.labels" . | nindent 4 }}
{{- end }}
