#!/usr/bin/env bash
# Build the exploratory comparison environment:
#   - one host-side Forgejo container on the shared 'kind' Docker network
#   - two kind clusters (leancd-compare, argocd-compare)
# Idempotent: re-running tears down any prior compare environment first.
set -euo pipefail
source "$(dirname "$0")/lib/common.sh"

# --- helpers (must be defined before use) -----------------------------------
forgejo_admin_list() {
    docker exec "$FORGEJO_CONTAINER" su -c \
        "forgejo admin user list -c /data/gitea/conf/app.ini -w /var/lib/gitea" git 2>/dev/null
}

log "=== leancd vs Argo CD exploratory environment setup ==="

# 1. Prerequisites
for c in docker kind kubectl curl jq git; do
    command -v "$c" >/dev/null 2>&1 || { log "missing required tool: $c"; exit 1; }
done

# 2. Cleanup (idempotent)
log "cleaning up any prior compare environment..."
docker rm -f "$FORGEJO_CONTAINER" >/dev/null 2>&1 || true
kind delete cluster --name "$LEANCD_CLUSTER" >/dev/null 2>&1 || true
kind delete cluster --name "$ARGOCD_CLUSTER" >/dev/null 2>&1 || true
rm -f "$STATE_FILE"

# 3. Start Forgejo on the shared 'kind' network
log "starting Forgejo container '$FORGEJO_CONTAINER' on network '$FORGEJO_DOCKER_NET'..."
docker run -d --name "$FORGEJO_CONTAINER" \
    --network "$FORGEJO_DOCKER_NET" \
    -p "${FORGEJO_HOST_PORT}:3000" \
    -e FORGEJO__security__INSTALL_LOCK=true \
    -e FORGEJO__database__DB_TYPE=sqlite3 \
    -e FORGEJO__server__ROOT_URL="http://127.0.0.1:${FORGEJO_HOST_PORT}/" \
    -e FORGEJO__server__LOCAL_ROOT_URL="http://127.0.0.1:3000/" \
    codeberg.org/forgejo/forgejo:7 >/dev/null

# 4. Kick off both kind clusters in parallel (node image is already cached)
log "creating kind clusters in parallel..."
LEANCD_CLUSTER_LOG="$(mktemp -t leancd-cluster.XXXXXX.log)"
ARGOCD_CLUSTER_LOG="$(mktemp -t argocd-cluster.XXXXXX.log)"
( kind create cluster --name "$LEANCD_CLUSTER" >"$LEANCD_CLUSTER_LOG" 2>&1 ) &
PID_LEAN=$!
( kind create cluster --name "$ARGOCD_CLUSTER" >"$ARGOCD_CLUSTER_LOG" 2>&1 ) &
PID_ARGO=$!

# 5. While clusters come up, wait for Forgejo DB, then bootstrap it
log "waiting for Forgejo to initialise its DB (admin CLI to respond)..."
wait_for 240 "forgejo admin CLI ready" forgejo_admin_list

if ! forgejo_admin_list 2>/dev/null | grep -q "$FORGEJO_USER"; then
    log "creating Forgejo admin user '$FORGEJO_USER'..."
    docker exec "$FORGEJO_CONTAINER" su -c \
        "forgejo admin user create --admin --username ${FORGEJO_USER} --password ${FORGEJO_PASS} \
         --email ${FORGEJO_EMAIL} --must-change-password=false \
         -c /data/gitea/conf/app.ini -w /var/lib/gitea" git >/dev/null 2>&1 \
        || log "WARN: admin user create returned non-zero (may already exist)"
fi

log "ensuring repo '${REPO_OWNER}/${REPO}' exists (auto_init=true)..."
# Create the repo; ignore the 409 if it already exists.
http_code="$(curl -sS -o /dev/null -w '%{http_code}' -X POST \
    -u "${FORGEJO_USER}:${FORGEJO_PASS}" -H 'Content-Type: application/json' \
    -d "{\"name\":\"${REPO}\",\"private\":true,\"auto_init\":true,\"default_branch\":\"main\",\"description\":\"leancd vs Argo CD comparison\"}" \
    "$(forgejo_host_url)/api/v1/user/repos")" || true
case "$http_code" in
    200|201) log "  repo created (http $http_code)";;
    409)     log "  repo already exists (http 409)";;
    *)       log "WARN: repo create http $http_code";;
esac

# 6. Wait for both clusters
log "waiting for kind clusters to finish creating..."
if ! wait "$PID_LEAN"; then
    log "FAIL: leancd cluster creation:"; cat "$LEANCD_CLUSTER_LOG"; exit 1
fi
if ! wait "$PID_ARGO"; then
    log "FAIL: argocd cluster creation:"; cat "$ARGOCD_CLUSTER_LOG"; exit 1
fi
log "  kind-${LEANCD_CLUSTER} ready"
log "  kind-${ARGOCD_CLUSTER} ready"

# 7. Resolve Forgejo's IP on the kind network (reachable from Pods)
FORGEJO_IP="$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$FORGEJO_CONTAINER")"
if [[ -z "$FORGEJO_IP" ]]; then
    log "FAIL: could not resolve Forgejo IP on network '$FORGEJO_DOCKER_NET'"; exit 1
fi

# 8. Persist dynamic state for the other scripts
cat > "$STATE_FILE" <<EOF
# Generated by setup.sh — Forgejo's IP on the shared kind network.
export FORGEJO_IP="${FORGEJO_IP}"
EOF

log "=== setup done ==="
log "Forgejo host URL : $(forgejo_host_url)"
log "Forgejo git URL  : $(forgejo_git_url)  (used by both controllers)"
log "Forgejo push URL : $(forgejo_push_url)  (used by this driver)"
log "leancd context   : kind-${LEANCD_CLUSTER}"
log "argocd context   : kind-${ARGOCD_CLUSTER}"
log "state file       : $STATE_FILE"
